// Static image imports (`import logo from "./logo.png"`) get their type from
// next/image-types/global. Next normally wires that in via next-env.d.ts — but
// that file is gitignored and only regenerated by `next build`/`dev`, so CI's
// typecheck step (which runs before build) has no declaration for image modules.
// Re-reference it here, in a tracked file, so image imports typecheck everywhere.
/// <reference types="next/image-types/global" />
