"use client";

import { useEffect, useRef, useState } from "react";
import {
  Type,
  FileText,
  ExternalLink,
  AlignLeft,
  Image as ImageIcon,
  PanelLeft,
  ImagePlus,
  Tag,
  EyeOff,
  Search,
  LayoutGrid,
  Trash2,
} from "lucide-react";
import { toast } from "sonner";
import { readPageMetaAction, savePageMetaAction, deletePageAction } from "@/lib/actions/authoring";
import { SettingsShell, Row, TextField, ToggleField, KeywordsField, SelectField } from "./SettingsUI";

type Meta = Record<string, unknown>;
const str = (v: unknown) => (typeof v === "string" ? v : "");
const arr = (v: unknown) => (Array.isArray(v) ? (v as string[]) : []);

const MODES = [
  { value: "", label: "Default" },
  { value: "wide", label: "Wide" },
  { value: "custom", label: "Custom" },
  { value: "center", label: "Center" },
];

// Page settings — edits the page's frontmatter. Keeps the full frontmatter object so keys we
// don't surface (groups, noindex, …) are preserved; only managed keys are overwritten.
export function PageSettings({
  org,
  site,
  branch,
  slug,
  onClose,
  onSaved,
}: {
  org: string;
  site: string;
  branch: string;
  slug: string;
  onClose: () => void;
  onSaved: () => void;
}) {
  const [meta, setMeta] = useState<Meta | null>(null);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    readPageMetaAction(org, site, branch, slug).then((res) => setMeta("error" in res ? {} : res.data));
    return () => void (timer.current && clearTimeout(timer.current));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const patch = (key: string, value: unknown) => {
    setMeta((prev) => {
      const next = { ...(prev ?? {}), [key]: value };
      if (timer.current) clearTimeout(timer.current);
      timer.current = setTimeout(() => {
        savePageMetaAction(org, site, branch, slug, next).then(() => onSaved());
      }, 500);
      return next;
    });
  };

  const del = async () => {
    if (!window.confirm(`Delete "${str(meta?.title) || slug}"? This removes the page on publish.`)) return;
    const res = await deletePageAction(org, site, branch, slug);
    if ("error" in res) toast.error(res.error);
    else {
      toast.success("Page deleted");
      onSaved();
      onClose();
    }
  };

  if (!meta) {
    return (
      <SettingsShell title="Page settings" onClose={onClose}>
        <div className="pv-settings-loading">Loading…</div>
      </SettingsShell>
    );
  }

  const hidden = meta.hidden === true;

  return (
    <SettingsShell
      title="Page settings"
      onClose={onClose}
      actions={
        <>
          <button
            type="button"
            aria-label={hidden ? "Show page" : "Hide page"}
            className={`pv-settings-iconbtn${hidden ? " is-active" : ""}`}
            onClick={() => patch("hidden", !hidden)}
          >
            <EyeOff className="h-4 w-4" />
          </button>
          <button type="button" aria-label="Delete page" className="pv-settings-iconbtn is-danger" onClick={del}>
            <Trash2 className="h-4 w-4" />
          </button>
        </>
      }
    >
      <Row icon={Type} label="Title">
        <TextField value={str(meta.title)} placeholder="Page title" onChange={(v) => patch("title", v)} />
      </Row>
      <Row icon={FileText} label="Slug">
        <TextField value={slug || "index"} disabled onChange={() => {}} />
      </Row>
      <Row icon={ExternalLink} label="External URL">
        <TextField value={str(meta.url)} placeholder="Enter external url" onChange={(v) => patch("url", v)} />
      </Row>
      <Row icon={AlignLeft} label="Description">
        <TextField
          value={str(meta.description)}
          placeholder="Enter description"
          onChange={(v) => patch("description", v)}
        />
      </Row>
      <Row icon={ImageIcon} label="Icon">
        <TextField value={str(meta.icon)} placeholder="Icon name (e.g. rocket)" onChange={(v) => patch("icon", v)} />
      </Row>
      <Row icon={PanelLeft} label="Sidebar title">
        <TextField
          value={str(meta.sidebarTitle)}
          placeholder="Enter sidebar title"
          onChange={(v) => patch("sidebarTitle", v)}
        />
      </Row>
      <Row icon={ImagePlus} label="OG Image URL">
        <TextField
          value={str(meta["og:image"])}
          placeholder="Enter URL (auto generated by default)"
          onChange={(v) => patch("og:image", v)}
        />
      </Row>
      <Row icon={Tag} label="Tag">
        <TextField value={str(meta.tag)} placeholder="Badge label (e.g. New)" onChange={(v) => patch("tag", v)} />
      </Row>
      <Row icon={EyeOff} label="Hidden">
        <ToggleField on={hidden} onChange={(v) => patch("hidden", v)} onLabel="Yes" offLabel="No" />
      </Row>
      <Row icon={Search} label="Keywords">
        <KeywordsField value={arr(meta.keywords)} onChange={(v) => patch("keywords", v)} />
      </Row>
      <Row icon={LayoutGrid} label="Mode">
        <SelectField value={str(meta.mode)} options={MODES} onChange={(v) => patch("mode", v)} />
      </Row>
    </SettingsShell>
  );
}
